- name: setup redis server
  hosts: redis
  become: yes
  tasks: 
  - name: disable redis module
    ansible.builtin.command: dnf module disable redis -y

  - name: enable redis module
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: install redis
    ansible.builtin.package:
      name: redis
      state: present

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0 '

  - name: disable protected module
    ansible.builtin.lineinfile:
      path: /etc/mongod.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes                 