- name: setup shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql  

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent  

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory    

  - name: delete shipping application
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent      

  - name: download shipping application
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip"
      dest: "/tmp/shipping.zip"        

  - name: extract code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes 

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app   

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: shipping
      enabled: yes
      state: started
      daemon_reload: true    

  - name: copy shipping service file 
    ansible.builtin.service:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: import shipping data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.malleswari.fun
      login_user: root
      login_password: RoboShop@1 
      target: "{{ item }}" 
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  # - name: daemon reload enable and restart
  #   ansible.builtin.systemd_service:
  #     name: shipping
  #     enabled: yes
  #     state: restarted
  #     daemon_reload: true            